### Numpy Library

- Processing N-Dimensional Arrays


In [2]:
import numpy as np
li=[1,2,3]
a=np.array(li)
a

array([1, 2, 3])

In [3]:
type(a)


numpy.ndarray

In [4]:
import numpy as np
li=[1,2,3,'x']
a=np.array(li)
a

array(['1', '2', '3', 'x'], dtype='<U11')

In [5]:
b=np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
rn=np.random.randint(0,100,size=10)
rn

array([32, 98, 76, 25, 43,  6, 97, 20, 56, 82])

In [12]:
#3 d matrx
m3=np.random.randint(0,2,size=(3,3))
m3

array([[1, 1, 0],
       [1, 0, 0],
       [0, 1, 1]])

In [16]:
m3=np.random.randint(1,4,size=(3,3))
m3

array([[1, 2, 1],
       [2, 1, 2],
       [3, 2, 1]])

In [17]:
m3[0][2]

1

In [18]:
m3=np.random.randint(1,4,size=(3,3,3))
m3

array([[[1, 3, 2],
        [1, 3, 3],
        [3, 3, 3]],

       [[1, 3, 3],
        [2, 3, 2],
        [2, 3, 3]],

       [[2, 3, 2],
        [1, 3, 3],
        [2, 2, 1]]])

In [19]:
m3=np.random.randint(1,4,size=(3,3,3,3))
m3

array([[[[3, 2, 1],
         [2, 1, 2],
         [2, 2, 1]],

        [[3, 2, 3],
         [3, 1, 3],
         [1, 1, 2]],

        [[2, 2, 3],
         [3, 1, 2],
         [1, 2, 2]]],


       [[[1, 1, 3],
         [1, 3, 3],
         [2, 2, 2]],

        [[2, 1, 3],
         [2, 2, 3],
         [2, 1, 3]],

        [[1, 1, 2],
         [2, 3, 1],
         [1, 3, 2]]],


       [[[1, 2, 1],
         [1, 2, 1],
         [3, 3, 1]],

        [[3, 3, 2],
         [3, 3, 3],
         [2, 1, 2]],

        [[3, 2, 1],
         [3, 3, 3],
         [1, 1, 3]]]])

In [20]:
m3[2][2][2][2]

3

In [21]:
m3[2][2][2][1]

1

In [22]:
m3.ndim #no.of dimensions

4

In [23]:
m3.size #No.of elements

81

In [24]:
m3.shape

(3, 3, 3, 3)

In [26]:
m3.dtype

dtype('int32')

In [27]:
m3.itemsize

4

In [28]:
m3.nbytes

324

In [38]:
m3=np.random.randint(1,4,size=(3,3))
m3

array([[3, 1, 1],
       [3, 1, 2],
       [2, 2, 3]])

In [42]:
m3[2][-1]

3

In [43]:
m3[0][0]

3

In [44]:
m3[0,0]

3

In [45]:
m3[::-1, :: -1] #trainsposing

array([[3, 2, 2],
       [2, 1, 3],
       [1, 1, 3]])

In [48]:
m3[:1, :2]

array([[3, 1]])

In [49]:
m3[:2, :2]

array([[3, 1],
       [3, 1]])

In [50]:
print(m3[:2,:2]) #it remove comas

[[3 1]
 [3 1]]


In [51]:
print(m3)

[[3 1 1]
 [3 1 2]
 [2 2 3]]


In [53]:
print(m3[0, :])

[3 1 1]


In [55]:
x3_sub =m3[:2, :2]
print(x3_sub)

[[3 1]
 [3 1]]


In [57]:
x=[1,2,3,4,5,6,7,8,9,10,11,12,13,14]
x1,x2,x3=np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [4 5] [ 6  7  8  9 10 11 12 13 14]


In [59]:
a=np.array([1,2,3,4,5,6,7,8])
b=a+1
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
a.shape

(8,)

### Pandas

**Use Cases** 
- Data Cleaning
- Data Transformation
- Data Analysis

**Notations**
- Series
- DataFrames

In [64]:
import pandas as pd

internal1={'s1':21, 's2':18, 's3': 24}
internal1=pd.Series(internal1)
internal1

s1    21
s2    18
s3    24
dtype: int64

In [66]:
internal2={'s1':31, 's2':88, 's3': 44}
internal2=pd.Series(internal2)
internal2

s1    31
s2    88
s3    44
dtype: int64

In [74]:
final={'internal':internal1, 'internal2':internal2}
final=pd.DataFrame(final)
final

internal  internal2
s1        31         31
s2        88         88
s3        44         44

In [76]:
#DataFrame object can view 2dimensional way of data
final={'internal1':internal1, 'internal2':internal2}
final=pd.DataFrame(final)
final['internal1']

s1    31
s2    88
s3    44
Name: internal1, dtype: int64

In [77]:
final.values #list of all rows

array([[31, 31],
       [88, 88],
       [44, 44]], dtype=int64)

In [78]:
final.columns #names of all columns

Index(['internal1', 'internal2'], dtype='object')

In [80]:
final.values[2]

array([44, 44], dtype=int64)

In [81]:
final.values[2,0]

44

In [83]:
# or
final.values[2][0]

44

In [87]:
for row in final.values:
    print('Internal1 - ',row[0] , ' internal2 - ',row[1])

Internal1 -  31  internal2 -  31
Internal1 -  88  internal2 -  88
Internal1 -  44  internal2 -  44


In [91]:
final.loc['s4']=[15,18]
final

internal1  internal2
s1         31         31
s2         88         88
s3         44         44
3          15         18
s4         15         18

In [92]:
final.drop(3)

internal1  internal2
s1         31         31
s2         88         88
s3         44         44
s4         15         18

In [93]:
final

internal1  internal2
s1         31         31
s2         88         88
s3         44         44
3          15         18
s4         15         18

In [98]:
final=final.drop[3]
final

AttributeError: 'function' object has no attribute 'drop'

In [99]:
final.values[2]=[23,56]
final

AttributeError: 'function' object has no attribute 'values'

In [100]:
# Reading CSV File Data
import pandas as pd
incomedf=pd.read_csv('DataFiles/income.csv')
incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [101]:

incomedf.values

array([['04000US01', 'Alabama', 37150, 37952, 42212, 44476, 39980, 40933,
        42590, 43464, 41381],
       ['04000US02', 'Alaska', 55891, 56418, 62993, 63989, 61604, 57848,
        57431, 63648, 61137],
       ['04000US04', 'Arizona', 45245, 46657, 47215, 46914, 45739, 46896,
        48621, 47044, 50602],
       ['04000US05', 'Arkansas', 36658, 37057, 40795, 39586, 36538,
        38587, 41302, 39018, 39919],
       ['04000US06', 'California', 51755, 55319, 55734, 57014, 56134,
        54283, 53367, 57020, 57528]], dtype=object)

In [102]:
# Extract Income of all States in year 2013
#California:57528
for row in incomedf.values:
    print(row[1], ':',row[-1])

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [104]:
# Average income of State Arizona
sum=0
for i in range(2,11):
    sum += incomedf.values[2][i]
print(sum/len(incomedf.values[2][2:]))

47214.77777777778


In [106]:
# Average income of all states in year 2012
sum=0
for row in incomedf.values:
    sum += row[-2]
print(sum/len(incomedf.values))

50038.8
